#!/bin/bash
# Example:
# text-01.txt
# 1
# 2
# 3
# 4
# text-02.txt
# a
# b
# c
# d
# result.txt
# 1
# a
# 2
# b
# 3
# c
# 4
# d
###########################
LASTLINEONE="0"
LASTLINETWO="0"
LASTLINEALL="0"
TEXTONE="text-01.txt"
TEXTTWO="text-02.txt"
RESULTTEXT="result.txt"
STRINGONE=""
STRINGTWO=""
LINE="1"
if [ -f "$TEXTONE" ]
then
LASTLINEONE=`cat "$TEXTONE" | wc -l`
else
echo ""
echo "text-01 not found. Exiting."
echo ""
exit
fi
if [ -f "$TEXTTWO" ]
then
LASTLINETWO=`cat "$TEXTTWO" | wc -l`
else
echo ""
echo "text-02 not found. Exiting."
echo ""
exit
fi
if [ "$LASTLINETWO" -lt "$LASTLINEONE" ]
then
echo ""
echo "text-02 has less lines than text-01. Exiting."
echo ""
exit
fi
if [ "$LASTLINEONE" -lt "$LASTLINETWO" ]
then
echo ""
echo "text-01 has less lines than text-02. Exiting."
echo ""
exit
fi
# text-01.txt seems to have the same lines with text-02.txt
LASTLINEALL=$((LASTLINEONE+1))
rm "$RESULTTEXT"
while "$LINE" -lt "$LASTLINEALL"
STRINGONE=`cat "$TEXTONE" | sed -n "$LINE"p`
STRINGTWO=`cat "$TEXTTWO" | sed -n "$LINE"p`
echo "$STRINGONE" >> "$RESULTTEXT"
echo "$STRINGTWO" >> "$RESULTTEXT"
LINE=$((LINE+1))
done
echo ""
echo "Done."
echo ""
